# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Metrics.NET project and run tests

on:
  push:
    branches: [ "master" ]
    paths: [ "Src/**" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -warnaserror --no-restore --configuration Release Src/Metrics/Metrics.csproj
    - name: Test
      run: dotnet test --verbosity normal --no-restore --configuration Release
